management:
  endpoints:
    web:
      base-path: "/management"
      exposure:
        include: "*"
    server:
      port: "8089"
  endpoint:
    health:
      show-details: "ALWAYS"

info:
  app:
  name: Spring Sample Application
  description: This is my first spring boot application
  version: 1.0.0
