management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, trace, beans, mappings

info:
  app:
  name: Spring Sample Application
  description: This is my first spring boot application
  version: 1.0.0
