management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "ALWAYS"

info:
  app:
  name: Spring Sample Application
  description: This is my first spring boot application
  version: 1.0.0
